# Generated by Django 6.0 on 2025-12-23 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author_initials', models.CharField(default='DHR', max_length=10)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(help_text='Brief summary for listings', max_length=500)),
                ('category', models.CharField(choices=[('psychology', 'Psychology & Behavior'), ('technology', 'Technology & Algorithms'), ('sociology', 'Sociology & Trends'), ('data', 'Data Analysis'), ('ethics', 'Ethics & Policy'), ('culture', 'Culture & Society')], max_length=20)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated read time in minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
