# Generated by Django 6.0 on 2025-12-25 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_initials',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Dating Hub Research Team', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True, default='Dating Hub Research Team provides insights into modern dating trends, relationship psychology, and data-driven advice for successful connections.', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO (if republished)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for SEO and accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Custom meta description (optional). Leave blank to use excerpt.', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom meta title (optional). Leave blank to use post title.', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('research', 'Research Insights'), ('trends', 'Dating Trends'), ('technology', 'Technology & Dating'), ('psychology', 'Relationship Psychology'), ('advice', 'Practical Advice')], default='research', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Use proper HTML headings (h2, h3) for SEO'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Meta description - keep under 160 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1200x630px for social sharing', null=True, upload_to='blog/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes (calculated at 200 words/min)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Auto-generated from title', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Keep under 60 characters for optimal SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug', 'status'], name='blog_blogpo_slug_0e8f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published_date', 'status'], name='blog_blogpo_publish_1485bd_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', 'status'], name='blog_blogpo_categor_a21b24_idx'),
        ),
    ]
