# Generated by Django 5.0.6 on 2025-12-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('survey_type', models.CharField(choices=[('completed', 'Completed Survey - Personalized Recommendations'), ('skipped', 'Skipped Survey - Basic Recommendations')], default='completed', max_length=50, verbose_name='Survey Type')),
                ('answers', models.JSONField(blank=True, help_text='JSON format of all survey questions and answers', null=True, verbose_name='Survey Answers')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('processed', models.BooleanField(default=False, help_text='Mark as processed when recommendations have been sent', verbose_name='Processed')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this submission', verbose_name='Admin Notes')),
            ],
            options={
                'verbose_name': 'Survey Submission',
                'verbose_name_plural': 'Survey Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['email'], name='research_su_email_848952_idx'), models.Index(fields=['submitted_at'], name='research_su_submitt_66e34a_idx'), models.Index(fields=['processed'], name='research_su_process_dec78e_idx')],
            },
        ),
    ]
